name: PHP Composer

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: read

jobs:
  standard:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Validate composer.json and composer.lock
      #  run: composer validate --strict

      # - name: Cache Composer packages
      #   id: composer-cache
      #   uses: actions/cache@v3
      #   with:
      #     path: vendor
      #     key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-php-

      - name: Composer Install
        run: composer install --prefer-dist --no-progress

      - name: PHPUnit
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --log-junit junit_report.xml --coverage-clover clover.xml --coverage-text --colors=never

      - name: PHPStan
        run: ./vendor/bin/phpstan

      - name: PHP_CodeSniffer
        run: ./vendor/bin/phpcs

      - name: CodeCov
        uses: codecov/codecov-action@v3

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
